[package]
name = "command_line_arguments"
version = "0.1.0"

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
handlebars = "1.0.3"
serde = "1.0.70"
serde_derive = "1.0"
serde_json = "1.0"
log = { version = "0.4", features = ["std", "serde"] }
env_logger = "0.5.13"

