[package]
name = "threads_synchronization_and_parallelism"
version = "0.1.0"

[dependencies]
crossbeam = "0.3.2"
crossbeam-channel = "0.2.6"
rayon = "1.0.2"
rand = "0.5"
mythread = { path = "./mythread" }
