debug = false
priority = 32
key = "189rjfadoisfj8923fjio"

arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

[[items]]
name = "1"

[[items]]
name = "2"

[place]
number = 1
name = "Torre di Pisa"
longitude = 43.7224985


[place.creator]
name = "John Smith"
